# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f7ffb68200f85ea9978fb288053bb4e295021733f9f8626ae44f422393fb6b9f781d1d71ab3662c8b6d478ab264c15b6ecdbeaa4363f76541a36689461554d

test:
  secret_key_base: 32b909bcded66c8317f1aa408b56485875293800c027ceb214ccd2815c2413eed07ef6c27d72ca4fff97d88e33e8a1bdfaa3de6f61b249a07f280364ab924343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
